---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - При нажатии на лого 'Hexlet Store' должен происходить переход на главную страницу
  - Пользователь должен иметь возможность удалять товары из корзины
  - Должна иметься возможность конвертации валют исходя из региона или охвата аудитории
  - Необходим запрет на введение отрицательных значений в диапазон цен
  - Сайт должен предоставлять актуальную информацию о наличии товаров
  - Пользователь видит на странице товара название, рейтинг, цена со скидкой и без скидки
  - Пользователь может добавить товар в корзину и продолжить выбирать товары в каталоге
  - Корзина будет хранится в сессии браузера
  - На странице корзины пользователь cможет удалить товар из корзины, продолжить выбирать товары в каталоге
  - Возможность оформить заказ с переходом на страницу оплаты
